const express=require('express');
const cors=require('cors');
const authRoute=require('./routes/auth.route');
const userRoute=require('./routes/user.route');
const categoryRoute=require('./routes/category.route');
const productRoute=require('./routes/product.route');
const cartRoute=require("./routes/cart.route");
const orderRoute = require('./routes/order.route');
const errorMiddleware = require('./middlewares/error.middleware');
const app=express();
app.use(express.json());
app.use(cors());
app.use('/api/auth',authRoute);
app.use('/api/users',userRoute);
app.use('/api/categories',categoryRoute);
app.use('/api/products',productRoute);
app.use("/api/cart",cartRoute);
app.use('/api/orders', orderRoute);
app.use(errorMiddleware);
module.exports=app;

